const callJoinedNsps = {
  prefix: "call",
  wsEvents: {
    JOIN_ROOM: "JOIN_ROOM",
    ALL_USERS_IN_ROOM: "ALL_USERS_IN_ROOM",
    GET_RTP_CAPABILITIES: "GET_RTP_CAPABILITIES",
    CREATE_WEB_RTC_TRANSPORT: "CREATE_WEB_RTC_TRANSPORT",
    PRODUCER_TRANSPORT_CONNECT: "PRODUCER_TRANSPORT_CONNECT",
    PRODUCER_TRANSPORT_PRODUCE: "PRODUCER_TRANSPORT_PRODUCE",
    NEW_PRODUCER: "NEW_PRODUCER" 
  },
};

module.exports = {
  callJoinedNsps,
};
